// Generated by CoffeeScript 1.4.0
(function() {
  var click, depChart, isCollapsed, sysChart;

  sysChart = null;

  depChart = null;

  window.addEventListener('load', function() {
    var container;
    if (data.systemHierarchy != null) {
      container = document.getElementById('system-hierarchy-chart');
      sysChart = new window.SysHierarchyChart(data, {
        container: container
      });
    }
    d3.selectAll('g').on('click', click);
    return d3.selectAll('g').on('contextmenu', click);
  });

  click = function(datum) {
    var button, ele;
    button = d3.event.button;
    ele = datum.element;
    if (button === 0 && !isCollapsed(ele)) {
      return sysChart.zoom(datum);
    } else if (button > 0 && isCollapsed(ele)) {
      return sysChart.expand(datum);
    } else if (button > 0) {
      return sysChart.collapse(datum);
    }
  };

  isCollapsed = function(element) {
    return element.classList.contains('collapsed');
  };

}).call(this);
